"""Subclass of Window, which is generated by wxFormBuilder."""

import wx
import memoApp

# Implementing Window
class memoAppWindow( memoApp.Window ):
	def __init__( self, parent ):
		memoApp.Window.__init__( self, parent )

	# Handlers for Window events.
	def m_File_NewOnMenuSelection( self, event ):
		# TODO: Implement m_File_NewOnMenuSelection
		pass

	def m_File_SaveOnMenuSelection( self, event ):
		# TODO: Implement m_File_SaveOnMenuSelection
		pass

	def m_File_OverwriteOnMenuSelection( self, event ):
		# TODO: Implement m_File_OverwriteOnMenuSelection
		pass

	def m_File_OpenOnMenuSelection( self, event ):
		# TODO: Implement m_File_OpenOnMenuSelection
		pass


