"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import TestApp

# Implementing MyFrame1
class MyProject1MyFrame1(TestApp.MyFrame1):
	def __init__( self, parent ):
		TestApp.MyFrame1.__init__(self, parent)

	# Handlers for MyFrame1 events.
	def m_button1OnButtonClick( self, event ):
		# TODO: Implement m_button1OnButtonClick
		pass


